### ISSUE TITLE
Turn off crane-php-stubs

### ISSUE THREAD

**Issue by mta59066** [HvyIndustries/crane-php-stubs#5]
What is the procedure to get stubs uninstalled? There is a way to turn off default php suggestions via `php.suggest.basic` but I cannot find a way to stop these stubs from being suggested even after uninstalling Crane all together.

**Comment by nevadascout** [comment]
They should not be suggested after Crane is uninstalled, but you can remove them by deleting the files from `%APPDATA%/Crane` on Windows, `~/Library/Preferences/Crane` on MacOS or `~/Crane` on Linux

**Comment by mta59066** [comment]
Thank you
